#Input is gene directory generated by Pangloss
#For each gene-cluster in the directory, the script takes the first fasta sequences and ignores the others
#Reason to do this is we want to input the accessory genes into pfam_scan.sh for functionality
#However, each gene-cluster file output by Pangloss will have between 1 and 41 copies of the gene making downstream parse difficfult
#We want a single representative of each cluster

#Core genes
for file in ~/panoct/clusters/core/faa/*
do
awk "/^>/ {n++} n>1 {exit} {print}" $file >> represents_core.aa
done

#Accessory genes
for file in ~/panoct/clusters/acc/faa/*
do
awk "/^>/ {n++} n>1 {exit} {print}" $file >> represents_accessory.aa
done
