#Input is the accessory gene directory generated by Pangloss
#For each gene-cluster in the directory, the script takes the first fasta sequences and ignores the others
#Reason to do this is we want to input the accessory genes into pfam_scan.sh for functionality
#However, each accessory gene file output by Pangloss will have  between 1 and 39 copies of the gene making downstream parse difficfult
#We want a single representative of each cluster

for file in ~/panoct/clusters/acc/faa/*
do
awk "/^>/ {n++} n>1 {exit} {print}" $file >> represents_accessory.aa
done
